[tox]
envlist =
    py{39, 310, 311, 312, 313, 314, 315}
    pypy3
    docs
isolated_build = True

[testenv]
commands = python -m unittest {posargs}
extras = all
install_command = python -I -m pip install --only-binary=hyperscan {opts} {packages}

[testenv:docs]
base_path = py312
commands = sphinx-build -aWEnqb html doc/source doc/build
deps = -rdoc/requirements.txt
extras =

[testenv:py315]
; hyperscan does not have a wheel for Python 3.15 yet.
extras =

[testenv:pypy3]
; hyperscan does not have wheels for PyPy.
extras =
